anchor_version = "0.25.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
lootbox_opener = "2qPL6aunS5v636TymUKmQAG2iW6gn7q94vShQb51iyMW"

[programs.testnet]
lootbox_opener = "2qPL6aunS5v636TymUKmQAG2iW6gn7q94vShQb51iyMW"

[programs.localnet]
lootbox_opener = "2qPL6aunS5v636TymUKmQAG2iW6gn7q94vShQb51iyMW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./deploy-token.json"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[[test.validator.clone]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 --bail tests/**/*.ts"
